# Usar una imagen base de Python ligera
FROM python:3.13.3-slim

# Definir el directorio de trabajo
WORKDIR /app

# Copiar el código fuente
COPY main.py /app/

# Comando para ejecutar la app
CMD ["python", "main.py"] 